name:                propellant
version:             0.1.0.0
github:              "ChrisPenner/propellant"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/propellant#readme>

default-extensions:
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- LambdaCase
- ViewPatterns
- TypeApplications
- TypeOperators
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- StandaloneDeriving
- TemplateHaskell
- RankNTypes

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- stm
- containers
- lattices
- intervals
- concurrency
- unordered-containers
- hashable
- semigroupoids

ghc-options:
  - -Wall
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  propellant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - propellant

tests:
  propellant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - propellant
